### PR TITLE
Add nixos-generators

### PR DESCRIPTION
**Pull request by nagy**
https://github.com/nix-community/nixos-generators

### CODE REVIEW

**Comment by zimbatm** [comment]
Hi, I believe this entry doesn't satisfy the utility point of the inclusion policy: https://github.com/NixOS/flake-registry#inclusion-policy . But let me know if I missed some arguments.

**Comment by nagy** [comment]
The main purpose of this PR is that people can always run `nix run nixos-generators` instead of `nix run github:nix-community/nixos-generators`, so its main purpose is only a shortcut.

> The shortcut must offer clear utility to the NixOS ecosystem; it is not intended to showcase random projects.

I would argue, that the project resides in the `nix-community` org implies already that it has some utility for the NixOS ecosystem.

> Common names should be avoided to prevent confusion...

`nixos-generators` seems pretty unique and explicit to me.

Feel free to close if you dont agree.

**Comment by akirak** [comment]
> The main purpose of this PR is that people can always run nix run nixos-generators instead of nix run github:nix-community/nixos-generators, so its main purpose is only a shortcut.

@nagy FYI, you can use `nix run nixpkgs#nixos-generators` for that with slightly more typing. The advantage of having a registry entry would be allowing to access `nixosModules` and `nixosGenerate` from inside a flake without adding an input. Apologies if you already know this.

**Comment by zimbatm** [comment]
Closing as nixos-generators is now available as `nixos-rebuild build-image`.

**Pull request closed without merging**
