### PR TITLE
Add `haskell.nix`

### PR DESCRIPTION
**Pull request by yvan-sraka**
https://github.com/input-output-hk/haskell.nix

### CODE REVIEW

**Comment by balsoft** [comment]
How do you plan to use this? AFAIU it will not work in the CLI (`error: 'haskell.nix' is not a valid flake ID`), and neither it will not work as an argument to `outputs` (since `haskell.nix` is not a valid Nix identifier), so you will have to specify it in `inputs` anyways. Perhaps use `haskell-nix` instead?

**Comment by yvan-sraka** [comment]
> How do you plan to use this?

I quote @hamishmack on issue https://github.com/input-output-hk/haskell.nix/issues/1557:

> This would allow things like:
> 
> ```
> nix run haskell-nix#hix -- init
> nix run haskell-nix#hix -- develop
> nix run haskell-nix#hix-build
> nix run haskell-nix#hix-shell
> ```
> 
> (it might be nice to have `haskell.nix` if that is allowed)

---

> AFAIU it will not work in the CLI (`error: 'haskell.nix' is not a valid flake ID`), and neither it will not work as an argument to `outputs` (since `haskell.nix` is not a valid Nix identifier), so you will have to specify it in `inputs` anyways. Perhaps use `haskell-nix` instead?

I updated the PR, now using `haskell-nix` as flake ID!

**Comment by zimbatm** [comment]
Hi, I believe this entry doesn't satisfy the utility point of the inclusion policy: https://github.com/NixOS/flake-registry#inclusion-policy . But let me know if I missed some arguments.

**Comment by yvan-sraka** [comment]
> Hi, I believe this entry doesn't satisfy the utility point of the inclusion policy: https://github.com/NixOS/flake-registry#inclusion-policy . But let me know if I missed some arguments. You might want to consider submitting it to the awesome-nix project instead.

Yes! I could get your point, I have no good counterargument in mind, and the project is already advertised on https://github.com/nix-community/awesome-nix/#haskell :)

**Pull request closed without merging**
