### PR TITLE
Update release version

### PR DESCRIPTION
**Pull request by jonringer**
bump from 19.09 to 20.09. Also, use the release channel, instead of the development branch.

### CODE REVIEW

**Comment by jonringer** [comment]
Should probably make this an entry in the release process

**Comment by jonringer** [comment]
bump cc @edolstra

**Comment by jonringer** [comment]
I guess it's not really a concern due to how branches are parsed.

**Comment by edolstra** [comment]
Yeah, I've removed this entry since it's no longer needed (846277a).

**Pull request closed without merging**
